// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SourcingManager.Data;

#nullable disable

namespace SourcingManager.Migrations
{
    [DbContext(typeof(SourcingDbContext))]
    [Migration("20260723231605_InicialProveedores")]
    partial class InicialProveedores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SourcingManager.Models.CategoriaProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoriasProveedor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Materia Prima"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Logística"
                        });
                });

            modelBuilder.Entity("SourcingManager.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RucONit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProveedorId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SourcingManager.Models.Proveedor", b =>
                {
                    b.HasOne("SourcingManager.Models.CategoriaProveedor", "CategoriaProveedor")
                        .WithMany("Proveedores")
                        .HasForeignKey("CategoriaProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaProveedor");
                });

            modelBuilder.Entity("SourcingManager.Models.CategoriaProveedor", b =>
                {
                    b.Navigation("Proveedores");
                });
#pragma warning restore 612, 618
        }
    }
}
